import { color } from './theme';

/** Temporary roles for screens that have not moved to `constants/theme` yet. */
export const Colors = {
  background: color.bg,
  backgroundSecondary: color.bg,
  backgroundGradient: [color.bg, color.bg, color.bg],
  surface: color.bg,
  card: color.bgElevated,
  cardSolid: color.bgElevated,
  border: color.hairline,
  borderSolid: color.hairline,
  text: color.text,
  textSecondary: color.textSecondary,
  textTertiary: color.textTertiary,
  textMuted: color.textTertiary,
  textPurple: color.textSecondary,
  primary: color.fill,
  primaryLight: color.textSecondary,
  primaryDark: color.text,
  pink: color.textSecondary,
  pinkLight: color.textSecondary,
  success: color.text,
  successLight: color.textSecondary,
  successDark: color.text,
  warning: color.textSecondary,
  warningLight: color.textSecondary,
  error: color.text,
  info: color.textSecondary,
  oldPrimary: color.text,
  oldSuccess: color.textSecondary,
};
